### ISSUE TITLE
Update to an npm version of `detective`?

### ISSUE THREAD

**Issue by geekytime** [thlorenz/rename-function-calls#1]
I'd like to be able to install 'browserify-shim' without having to download modules from GitHub.

Right now browserify-shim depends on `rename-function-calls` which uses:

```
"detective": "git://github.com/thlorenz/node-detective#fix-noargs"
```

Was there a PR against substack/node-detective for your fix-noargs branch?

**Comment by geekytime** [comment]
Aha! I finally found the PR. 

https://github.com/substack/node-detective/pull/29

It looks like an upgrade to `detective@2.4.1` or higher would work?

**Comment by fmal** [comment]
I'd also like to be able to install 'browserify-shim' without having to download from GitHub.
Please update.

**Comment by thlorenz** [comment]
Went out with version 0.1.1. Thanks for reminding me.
